// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
using System.IO;
using System.Reflection;

namespace SeleniumTest
{
    public class SuiteTests : IDisposable
    {
        public IWebDriver driver { get; private set; }
        public IDictionary<String, Object> vars { get; private set; }
        public IJavaScriptExecutor js { get; private set; }
        public SuiteTests()
        {
            
            driver = new ChromeDriver(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location));
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<String, Object>();
        }
        public void Dispose()
        {
            driver.Quit();
        }
        [Fact]
        public void LegalZoomProcess()
        {
            driver.Navigate().GoToUrl("https://www.legalzoom.com/business/business-formation/inc-overview.html");
            driver.Manage().Window.Size = new System.Drawing.Size(1920, 1020);
            driver.FindElement(By.Id("hero915-input")).Click();
            driver.FindElement(By.Id("hero915-input")).SendKeys("testcorp");
            driver.FindElement(By.CssSelector("#hero915-button > span")).Click();
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.CssSelector(".tw-py-\\[17px\\]")).Click();
            driver.FindElement(By.CssSelector(".btn > span")).Click();
            driver.FindElement(By.CssSelector(".btn > span")).Click();
            driver.FindElement(By.CssSelector(".radio-container:nth-child(1) label")).Click();
            driver.FindElement(By.CssSelector(".focus\\3Atw-bg-action-interact")).Click();
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.Id("state_autocomplete")).Click();
            driver.FindElement(By.Id("state_autocomplete")).SendKeys("services");
            driver.FindElement(By.CssSelector(".btn > span")).Click();
            driver.FindElement(By.CssSelector(".radio-container:nth-child(3) label")).Click();
            driver.FindElement(By.CssSelector(".btn > span")).Click();
            driver.FindElement(By.CssSelector(".radio-container:nth-child(2) label")).Click();
            driver.FindElement(By.CssSelector(".btn > span")).Click();
            Thread.Sleep(3000);
            driver.FindElement(By.CssSelector(".radio-container:nth-child(2) label")).Click();
            driver.FindElement(By.CssSelector(".btn > span")).Click();
            driver.FindElement(By.CssSelector(".radio-container:nth-child(2) label")).Click();
            driver.FindElement(By.CssSelector(".focus\\3Atw-bg-action-interact")).Click();
            driver.FindElement(By.CssSelector(".btn > span")).Click();
            Thread.Sleep(3000);
            driver.FindElement(By.CssSelector(".focus\\3Atw-bg-action-interact")).Click();
            driver.FindElement(By.CssSelector(".tw-mt-auto:nth-child(5) .btn")).Click();
            driver.FindElement(By.CssSelector("form > .tw-p-0")).Click();
            driver.FindElement(By.CssSelector(".btn > span")).Click();
            driver.FindElement(By.CssSelector(".tw-hidden > form > .tw-p-0")).Click();
            js.ExecuteScript("window.scrollTo(0,17)");
            driver.FindElement(By.CssSelector(".radio-container:nth-child(2) label")).Click();
            driver.FindElement(By.CssSelector(".btn > span")).Click();
            driver.FindElement(By.CssSelector("form > .tw-p-0")).Click();
            driver.FindElement(By.CssSelector(".tw-text-white:nth-child(2)")).Click();
            driver.FindElement(By.CssSelector("form > .tw-p-0")).Click();
            Thread.Sleep(3000);
            driver.FindElement(By.CssSelector(".btn")).Click();
        }
    }
}